services:
  next-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    command: pnpm next dev
    networks:
      - wisteria-network

networks:
  wisteria-network:
    external: true